### ISSUE TITLE
Wrong number of MPs for current election period

### ISSUE THREAD

**Issue by dennlinger** [rhymeswithcycle/openparliament#46]
We are currently working on a project that utilizes the openparliament API (great project by the way) and noticed that the resulting query to the /politicians/ API returns only 308 MPs (number of MPs during the period from 2011-2015), instead of the current 338 MPs.
Only after manually setting the limit to >338 are more politicians returned. And even then, only 333 results are listed, so there seem to be some of them missing, still.
I'm currently trying to find out which of them are missing, to maybe give a direction where to look.

**Comment by rhymeswithcycle** [comment]
Thanks for pointing this out! The endpoint was still returning all the MPs, but, as you point out, the pagination was set to 308 per page, so you'd have to follow the next-page link to get the remaining ones.

I've changed the pagination default to 338. The API should be returning 334 results, which is correct (4 seats are currently vacant).
